temperaturas_registradas_siete_mayo <- c(30,25.4,18.7,34,49,14.1)
temperaturas_registradas_ocho_mayo <- c(28.9,34.2,32.3,18,16,25.9)
temperaturas_registradas_nueve_mayo <- c(38.7,31.2,22.6,18.6,16.9,25.9)
t <- c(temperaturas_registradas_siete_mayo, temperaturas_registradas_ocho_mayo, temperaturas_registradas_nueve_mayo)
cat("Los valores de la temperatura de los tres días son ", t[])
cat("El elemento mínimo del vector es: ")
min(t)
cat("El elemento máximo del vector es: ")
max(t)
cat("La media de las temperaturas es: ")
mean(t)
cat("La mediana de las temperaturas es: ")
median(t)
cat("El vector ordenado de menor a mayor es: ")
sort(t)